# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Matt Ginelli
tagline:          'Highlights of the Lone Ensign'
description:      'Highlights of the Lone Ensign'
url:              http://mattberkeley.github.io
baseurl:          /

author:
  name:           'Matthew Ginelli'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mattberkeley/mattberkeley.github.io
