# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matt Ginelli
tagline:          'Highlights of the Lowly Ensign'
description:      
url:              http://mattberkeley.github.io
baseurl:          /

author:
  name:           'Matthew Ginelli'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mattberkeley/mattberkeley.github.io
